include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false

analyzer:
  exclude:
    - lib/**.*.dart
  errors:
    invalid_annotation_target: ignore
    avoid_catches_without_on_clauses: ignore
    sort_pub_dependencies: ignore
    lines_longer_than_80_chars: ignore
