name: layali_flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  auto_route: ^10.0.1
  awesome_dialog: ^3.2.1
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  chopper: ^8.1.0
  collection: ^1.19.1
  envied: ^1.1.1
  flex_color_scheme: ^8.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.1.0
  form_validator: ^2.1.1
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  http: ^1.3.0
  http_parser: ^4.1.2
  image_cropper: ^9.1.0
  image_picker: ^1.1.2
  injectable: ^2.5.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  page_view_dot_indicator: ^2.3.0
  pretty_chopper_logger: ^1.2.2
  recase: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  injectable_generator: ^2.7.0
  envied_generator: ^1.1.1
  chopper_generator: ^8.1.0
  flutter_gen_runner: ^5.10.0
  very_good_analysis: ^7.0.0


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/svg/
    - assets/images/
